### ISSUE TITLE
desyntheis doesn't work (cn server)

### ISSUE THREAD

**Issue by LittleNightmare** [daemitus/YesAlready#12]
I have select both “desyntheis" and "desyntheis (bulk)" but doesn't work. SalvageDialog keeps display. I use SomethingNeedDoing like the below code. it works. 
```
/waitaddon SalvageDialog
/click desynthesize
```

Does the global server change the structure? I am using YesAlredy in cn server. I see the commit about FFXIVClientStructs and ClickLib, but I find a problem. FFXIVClientStructs version in ClickLib is not the same as it in YesAlready. In addition, I haven't tested `/click desynthesize_checkbox` yet.

**Comment by rlynch-ironnet** [comment]
the checkbox click is broken. the bulk desynth worked this morning when I tested, but I'll try again tonight. I may need to make a debug DLL for you to test with.

**Comment by LittleNightmare** [comment]
@rlynch-ironnet I just test `/click desynthesize_checkbox`. In my point, it works. Although the checkbox doesn't change, the desynthesize button becomes clickable

**Comment by LittleNightmare** [comment]
it work https://github.com/daemitus/YesAlready/commit/ba58f2fb0a11322ba403b3c97a66c975d2599ec2
