### ISSUE TITLE
Request for Discard/Repair

### ISSUE THREAD

**Issue by Enzemo** [daemitus/YesAlready#13]
Sorry to raise as an issue, wasn't sure else to put it.

Cant get the regex patterns to work when manually entered, tried using the given example. I tried:

"/Repair all displayed items for \d+  gil\\?/"

But it didn't work.

Edit: Simple /Repair all display items for/ catches it

Could Repair items and Discarding/Discarding collectables be added to the menu too please?

Many thanks

**Comment by daemitus** [comment]
`/Repair all displayed items for \d+ gil?/`
just  worked for me

**Comment by Enzemo** [comment]
Hmm weird ! 

/Repair all displayed items for/ is working well enough thankfully

**Comment by daemitus** [comment]
maybe the escape on the question mark

**Comment by Enzemo** [comment]
![image](https://user-images.githubusercontent.com/11069930/114944287-3557b200-9e3f-11eb-9319-72fdf5c267b6.png)
There are slashes around it on the example, should they be there?

**Comment by daemitus** [comment]
dont quote it

**Comment by Enzemo** [comment]
Currently using 
/Repair all displayed items for/
and
/Collectability Rating/
to YesAlready the repairs and discarding collectables. Took a look at the code to submit a pr but i didn't want to mess anything up so I'll just leave them here if you want to close the issue
