### ISSUE TITLE
Does this skip cutscenes?

### ISSUE THREAD

**Issue by Terroosh** [daemitus/YesAlready#15]
I tried adding Skip and /Skip/ but when pressing ESC on cutscenes nothing happens. Also have "Hide plugin UI during cutscenes unchecked." Does YesAlready just not work during cutscenes?

**Comment by daemitus** [comment]
If the prompt shows up, it "should" work. provided the cutscene skip prompt is a YesNo widget.

**Comment by Terroosh** [comment]
Here's an example:

![canyoujustskipthecutsceneplease](https://user-images.githubusercontent.com/55752005/120728566-dd364700-c4a2-11eb-8a60-6b4dc069496c.png)

**Comment by daemitus** [comment]
yeah that's not a yesno box, its a 2 item listbox. not supported as of yet.

**Comment by Helios747** [comment]
what needs implementing to support listboxes?

I would also very much like to yesalready that specific dialog box and can write a bit of C#

**Comment by daemitus** [comment]
This is my previous work on selectstring and selecticonstrings. https://github.com/daemitus/ClickLib/blob/master/ClickLib/Clicks/ClickSelectString.cs

If that stuff still works, great. Then we would just need a way to store it in the config and to fetch the text out of the addon.

https://github.com/aers/FFXIVClientStructs/blob/main/FFXIV/Client/UI/AddonSelectString.cs
I don't see the immediate addon text there, but it can likely be found in the addon inspector in /xldata.

**Comment by daemitus** [comment]
So selectstring clicks do work currently, I just don't have any way of weaving this into the addon at the moment without adding an entirely new configuration type. 

I'll gladly take a PR if anyone wants to work on implementing it though.

**Comment by daemitus** [comment]
Covered under #7
