### ISSUE TITLE
Returns to starting point after death

### ISSUE THREAD

**Issue by SelfAfflicted** [daemitus/YesAlready#16]
I've been having an issue when I die in any dungeon or raid, with YesAlready enabled, I return to the starting point, inevitably locking me out of the current encounter. I don't have any entries that would cause this, as far as I can tell.
![image_2021-06-16_160326](https://user-images.githubusercontent.com/13339406/122293180-6181c480-cebc-11eb-86fb-64c7474f79af.png)

**Comment by daemitus** [comment]
What's the text when you're waiting for a res again?

**Comment by SelfAfflicted** [comment]
If I recall correctly, it's "Return to the starting point of <insert instance here>?"

**Comment by daemitus** [comment]
I don't see anything obvious but you'll want to wrap all your | operators
in parenthesis. Like the enter| leave... Is matching on only enter. I bet
it's one of those.

**Comment by SelfAfflicted** [comment]
That must've been it, no problem now, thank you! Great add-on btw, guess you saw how many prompts annoy the hell out of me.

**Comment by daemitus** [comment]
Glad to be of service :)
