### ISSUE TITLE
can  i ask how you compile this

### ISSUE THREAD

**Issue by DiggityMan420** [daemitus/YesAlready#19]
i would love to have this dll but dont know exacty how to compile it please explain an i can do it or if u would i would love it for release

**Comment by daemitus** [comment]
Add `https://github.com/daemitus/MyDalamudPlugins/raw/master/pluginmaster.json` to your 3rd party repos in the In-game settings and install normally.

**Comment by daemitus** [comment]
You'll need visual studio, rider, or maybe VSCode, and the correct .NET SDK. If your build environment is setup correctly, it usually just works.
