### ISSUE TITLE
Feature Request: hide on game launch and compiled binaries

### ISSUE THREAD

**Issue by Quezako** [daemitus/YesAlready#20]
Hello,

I have 2 feature requests : 
- is it possible to hide the addon on the game startup? it is always displayed on the game main screen.
- is it possible to release the compiled binaries? I've manage to compile the plugin, but it took me many hours, a lot of data to download and I had to edit some code manually. Since I'm not a C# developer, I suppose that I'm not the only one coping with that.

**Comment by daemitus** [comment]
You should be installing by adding https://github.com/daemitus/MyDalamudPlugins to your list of third party repos in game.  If you still want to compile it yourself, switch to release from debug.

**Comment by Quezako** [comment]
Thank you, I don't think that there was a repository when I've installed the addon, 2 months ago.
There is still on suggestion: is it possible to hide the addon on the game startup? it is always displayed on the game main screen.

**Comment by daemitus** [comment]
It's because you're compiling for debug. Switch the drop-down to release

**Comment by Quezako** [comment]
Ah yes, I had to manually delete the folder and then install from repo.
No it works perfectly! Thank you for this great addon!

**Comment by daemitus** [comment]
Glad to hear it worked out :)
