### ISSUE TITLE
Feature Request: Pressing OK when selling unique or 100% spiritbound items

### ISSUE THREAD

**Issue by bladehawkz** [daemitus/YesAlready#23]

**Comment by daemitus** [comment]
isnt this a yes/no dialog already?

**Comment by bladehawkz** [comment]
It's an 'OK' and 'Cancel' dialog, which doesn't seem to work, unless I'm missing something.

Just testing teleport which works, but using the text entry 
'This item is unique and untradeable. Are you certain you wish to sell it?'
doesn't do anything, the confirmation requirement still comes up.

**Comment by bladehawkz** [comment]
I'm an idiot and have a typo in my text entry. Closed.
