### ISSUE TITLE
Special chars like äöü not working correctly

### ISSUE THREAD

**Issue by Akurosia** [daemitus/YesAlready#3]
Some non english character like äöüß (from e.g. the german language) are not displayed/handeled correctly.

Following statement is captured when using the GUI (when you sell something at the retainer directly and wanna leave the retainer):
`Wenn du deinen Gehilfen wegschickst, kannst du die von ihm verkauften GegenstÃ¤nde nicht mehr zurÃ¼ckkaufen. MÃ¶chtest du trotzdem fortfahren?`
which should be `Wenn du deinen Gehilfen wegschickst, kannst du die von ihm verkauften Gegenstände nicht mehr zurückkaufen. Möchtest du trotzdem fortfahren?`

Problem is, that the system does only allow the first statement, not the second. Any chance make it work with utf-8? This should also capture some of french chars like é à ô

**Comment by daemitus** [comment]
I need to swap my game language and play around with it a bit.

**Comment by Bluefissure** [comment]
not sure whether https://github.com/daemitus/YesAlready/pull/4 will help

**Comment by daemitus** [comment]
Might be fixed now, give it a shot
