### ISSUE TITLE
Interfaces sometimes not appearing

### ISSUE THREAD

**Issue by GandalfTheGoat** [daemitus/YesAlready#38]
Trying to craft some Grade 3 wheels using the fabrication station in the company workshop and the interface for it is not appearing, 

The game is working as it should while in an interface but the interface is just not there, the only way to get out of it is by force closing the game in task manager. I can't use Esc to close the interface or alt F4 to close.

These are my settings:
![image](https://user-images.githubusercontent.com/9063939/141954021-ab9f15f2-8bcc-4792-96ee-c7de949c34fe.png)
![image](https://user-images.githubusercontent.com/9063939/141954034-72eb0388-bac5-4f24-8d9b-b86c26d57f52.png)
![image](https://user-images.githubusercontent.com/9063939/141954051-8a710e30-e4df-4c5d-8b29-3320bfb3bffb.png)
![image](https://user-images.githubusercontent.com/9063939/141953970-861bf7d5-b1a1-41e2-bb68-695c948032cb.png)

When I try and log out:
![image](https://user-images.githubusercontent.com/9063939/141954950-c957af39-4e60-4a0e-9469-d1391f856749.png)
[dalamud.log](https://github.com/daemitus/YesAlready/files/7544907/dalamud.log)

**Comment by daemitus** [comment]
might be fixed by now. please re-open if you have this happen again.
