### ISSUE TITLE
YesAlready instant ressurect issue

### ISSUE THREAD

**Issue by Spazzze** [daemitus/YesAlready#41]
Hello guys!

 I have an issue with plugin YesAlready. It keeps instantly press OK for resurrection at dungeons but it shouldn't. I've double checked if plugin is disabled - everything is ok and I am not ressurecting instantly. 

My config for plugin like this: 

![image](https://user-images.githubusercontent.com/8989548/143785068-78da4273-fe35-4db1-82a1-b5d9bb83c115.png)

As you can see I have only "Return to Foundation" and it shouldn't match with dungeon questions which is marked by arrows (I've saved them after being instantly ressurected). 

As you can see I also tried to use a negative look-ahead for regex but it didn't work. Can you help please what am I missing?

Or maybe you have an option to don't use some lines at dungeons?

**Comment by daemitus** [comment]
It is probably matching on Enter.*.
If i recall, its not case sensitive

**Comment by Spazzze** [comment]
Thanks!
