### ISSUE TITLE
Re-send retainers sometimes cancels after sending the retainer out.

### ISSUE THREAD

**Issue by Felys1998** [daemitus/YesAlready#42]
I haven't figured out how to 100% reproduce this, but occasionally when I click to complete a retainer venture and YesAlready sends it back out on the same venture, sometimes it'll return back to the menu and cancel the venture immediately, resulting in wasted venture tokens.

**Comment by Felys1998** [comment]
I think I might have a lead into why this is happening:

I believe I'm spam clicking during the retainer dialog or something that the extension is meant to skip, which is causing it to confirm on the cursor that is positioned at the "View venture report" selection after returning to the retainer's home menu, which results in it being clicked again and then the YesAlready behavior causes it to recall the venture. Is there any potential to add more state checking here?

**Comment by daemitus** [comment]
Ohhhhhh. 

View venture report is the same type of window as a venture result. I can check the text, but that'll be different for anyone with localized text. I'll come up with something.

**Comment by daemitus** [comment]
This is fixed in `.12` very simplistically. Targeting the 4 major languages I could get translations for, it does not  do anything if what is typically the "reassign" button has a text of Recall instead.

```
            if (buttonText == "Recall" ||
                buttonText == "中断する" ||
                buttonText == "Zurückrufen" ||
                buttonText == "Interrompre")
```
