### ISSUE TITLE
[Feature Request] Ok and Cancel Option

### ISSUE THREAD

**Issue by kgetit** [daemitus/YesAlready#44]
Unless I am overlooking it, please add check/option for Ok and Cancel. I don't know if this is loaded during the Character selection but with the relogging we have to do due to the 2002 crash and other errors this addon and option would help tremendously! Thank you in advance.

**Comment by daemitus** [comment]
are you talking about the "Login with XXX" character prompt at the login screen or the 2002 error prompt?

**Comment by kgetit** [comment]
Sorry if I was not as specific; I was asking for an "Ok" or "Cancel" option for pop-ups like the yes/no. I hope that made it more clear. Thank you in advance! My fingers from mouse clicking loves you!

**Comment by daemitus** [comment]
can you screenshot it? Alot of times Ok/Cancel windows are actually yes/no prompts under the hood.

**Comment by Eternita-S** [comment]
@kgetit world visit confirmation is yes/no with renamed buttons
regex `/Travel to [a-zA-Z]+\?/`

**Comment by kgetit** [comment]
I did not realize that it's just a yes/no function. Thank you for clarifying! I should have done the regex as Eternita sampled. It works.
