### ISSUE TITLE
Feature Request - Modifier Key For RetainerTaskResult

### ISSUE THREAD

**Issue by SelfAfflicted** [daemitus/YesAlready#45]
If it's possible, having a modifier key, such as holding shift, to either pause the auto selection of 'Reassign' and manually select or auto-switching to 'Confirm' for that current moment would be convenient. For now I try to remember to toggle this  in the config, when needed, but most times do not.

**Comment by daemitus** [comment]
I implemented a global disable everything key in `.10`  that should solve this, and many other situations where you temporarily want to turn it off.
