### ISSUE TITLE
Skip Cutscene from Airship/Submarine deploys

### ISSUE THREAD

**Issue by DingFandango** [daemitus/YesAlready#47]
The prompt to skip cutscenes isn't registered as one that can be selected by Yes Already. When adding the Last seen entry, I instead get the "Enter Estate Hall?" window prompt. 
![image](https://user-images.githubusercontent.com/23725766/146696363-28b2ca61-8e08-487d-b902-6b131b574bc9.png)
![image](https://user-images.githubusercontent.com/23725766/146696400-df631d0b-1ae1-4b36-97ba-7b79edc27a89.png)

**Comment by daemitus** [comment]
thats a list menu
