### ISSUE TITLE
teleport troubles

### ISSUE THREAD

**Issue by sauronshotdogs** [daemitus/YesAlready#48]
I have made 2 rules in thhe YesNo list

Accept teleport = no
![image](https://user-images.githubusercontent.com/95890035/146925733-32c7821a-aea3-4bcf-8037-0d8d5a518422.png)
Teleport to = yes
![image](https://user-images.githubusercontent.com/95890035/146925752-5b071aae-59d4-422c-a4ad-73e2e44c5d01.png)

This should make it so when I click aetherites on map, it doesn't prompt me, but it should still prompt me if a party member triggers the free teleport. It doesn't however.

Am I using wrong syntax, or is it a bug?

**Comment by daemitus** [comment]
I'm guessing it's "accept teleport to..." Which matches in the middle.
You'll likely need to make it a regex and add a ^ so it matches at the
start of the sentence.

**Comment by sauronshotdogs** [comment]
How would I go about doing that?

**Comment by daemitus** [comment]
A regex with yesalrdy, just add a / at the start and end. So /^Teleport to
.*/ Might work

**Comment by sauronshotdogs** [comment]
will try, thanks!
