### ISSUE TITLE
Modifier Key to auto click yes

### ISSUE THREAD

**Issue by DenL** [daemitus/YesAlready#49]
It would be greatly convenient if we could hold down a modifier key before triggering a dialogue to have it automatically select yes. Thank you!

**Comment by daemitus** [comment]
isnt this the point of setting the regexes, so you dont have to?

**Comment by DenL** [comment]
Sample use case: when on marketboard, I like having the confirmation dialogue so I don’t accidentally buy something when I don’t mean to. However sometime I’m spam buying 10’s of entries. Rather than setting up the regex and temporarily turning them on then off, having a modifier bypass would be great.

**Comment by daemitus** [comment]
Convincing argument, added.
