### ISSUE TITLE
Style buffers in text

### ISSUE THREAD

**Issue by Bluefissure** [daemitus/YesAlready#5]
I think there are some style buffers when different styles are in the dialog window.

![quicker_7dd5b4d7-292d-45ce-84ce-0e23a0dad965.png](https://i.loli.net/2021/03/17/SMlXB1QiRd6ujAL.png)
![quicker_b33686ce-a279-481c-b843-9d9dd68c5fb4.png](https://i.loli.net/2021/03/17/Ra1Jtrwn3AlYj6v.png)

More specifically, a buffer which starts with `02 48` is the begining of a style and a buffer which starts with `02 49` matches the end.

**Comment by daemitus** [comment]
Yeah, my solution for now had been to blast it with a regex

**Comment by Bluefissure** [comment]
Try to fix this in a tricky way, not sure whether this will mathc all the buffers.
https://github.com/daemitus/YesAlready/pull/6

**Comment by daemitus** [comment]
Used this with XL's SeString. Think it fixes it all. thanks :D
