### ISSUE TITLE
RetainerTaskAsk not skipping final Dialog after Update 1.2.0.11

### ISSUE THREAD

**Issue by netrox91** [daemitus/YesAlready#51]
Hello o/

First of all: Thanks for your great work!

Noticed that the final dialog before sending out the retainer again doesn't get skipped anymore like it did before.

**Comment by daemitus** [comment]
mmmm. ill take a look in a few when my retainers are back.

**Comment by ajhix36** [comment]
RetainerAskResult also is no longer working, after 1.2.0.12

**Comment by daemitus** [comment]
reverting everything until I can deal with it tonight/tomorrow.

**Comment by ajhix36** [comment]
Thanks boo, merry christmas <3

**Comment by daemitus** [comment]
should be good now, minus the other issue I cant fix as of yet.
