### ISSUE TITLE
Help text teleport regex

### ISSUE THREAD

**Issue by kaedys** [daemitus/YesAlready#52]
The existing regex pattern example in the `(?)` tooltip for teleporting is listed as `/Teleport to .*? for \d+ gil\?/`.  This fails to capture the changes to the teleport costs, which can now exceed 999 gil, and are comma-separated at the thousands place.  A direct fix would be `/Teleport to .*? for [\d,]+ gil\?/`, replacing the `\d+` token with the character group token `[\d,]+`.  However, for shear simplicity, I'd recommend `/^Teleport to .*\?$/`, which is the regex I wrote for teleports before an FC-mate pointed out the pattern in the help pop-up.

**Comment by daemitus** [comment]
done and done.
