### ISSUE TITLE
xivlauncher not detecting plugin

### ISSUE THREAD

**Issue by phireblast** [daemitus/YesAlready#55]
Instructions were to put the link in the dalamud settings, but when typing /pyes or /pyes help, the game isn't detecting it, as if the plugin isn't installed. For reference, here's how it's entered:

https://puu.sh/IzDFe/49f92a0019.png

**Comment by daemitus** [comment]
show me the whole window

**Comment by phireblast** [comment]
https://puu.sh/IzDJE/ff06404d3b.png

**Comment by daemitus** [comment]
hmm. try `https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/master/pluginmaster.json`

**Comment by daemitus** [comment]
wait wait wait.

**Comment by daemitus** [comment]
You need to install the plugin after adding the repo. Adding the repo URL just adds a new source to download plugins from.

**Comment by phireblast** [comment]
lmao, i'm an idiot. i now see the install part and the menus open fine.
