### ISSUE TITLE
Feature request: Skip all retainer dialogue

### ISSUE THREAD

**Issue by BeetleLord** [daemitus/YesAlready#60]
I would enjoy an option to streamline retainer interaction even more by automatically skipping all dialogue from them. I tried adding their names to the "Talk" feature and it did not work.

**Comment by daemitus** [comment]
add your target. the summoning bell.

**Comment by BeetleLord** [comment]
I see. This works, but it's not the most obvious thing. Perhaps a small note in the Help section for the Talk feature would help people realize this trick.
