### ISSUE TITLE
Bug Report for ContentFinderConfirm

### ISSUE THREAD

**Issue by jedahdemon** [daemitus/YesAlready#61]
Rarely I have run into an issue where the duty finder will pop and it will automatically confirm, then something happens during loading and it immediately kicks me back out of the dungeon with the 30 minute penalty timer. I only run into this issue when I have this feature enabled in the plugin, though I can't be certain what could be causing it.

**Comment by Grammernatzi** [comment]
Maybe because it is commencing as soon as the window pops up? The game might not like that and it'd be impossible to do otherwise. Perhaps a sort of delay could be added.

**Comment by marimelon** [comment]
Probably, This cause of the afk timer count is not reset when clicked by Clicklib.

**Comment by marimelon** [comment]
This does not seem to have occurred since the 6.1 update.
Does it still occur?
