### ISSUE TITLE
Feature Request: Selling multiple stacks at the retainer

### ISSUE THREAD

**Issue by MarkusWo** [daemitus/YesAlready#63]
Is there a possibility to sell multiple stacks of things from my retainer? I have 99 Atrociraptor Skins, but only want to put them up in 3 as few people want to buy full stacks. Would this be possible to do with YesAlready?

**Comment by Grammernatzi** [comment]
There is another plugin called Marketbuddy that both me and Dae use that lets you do this. I'd recommend using that instead.

**Comment by MarkusWo** [comment]
Marketbuddy indeed seems like it does exactly what I want and more. Thanks for the tip!
