### ISSUE TITLE
Feature Request: Retainer Task

### ISSUE THREAD

**Issue by monkeymc** [daemitus/YesAlready#69]
Hi Mr.daemitus.

![retainer](https://user-images.githubusercontent.com/12757694/163764347-1bf35dc0-165d-4347-8deb-d1b67d0199de.png)

Could u add "(Summoning Bell) (Complete)" in this feature?
When retainer assign done and auto assign.

Thank you.

**Comment by BrakTap** [comment]
Can already do that by using this

https://i.imgur.com/v6wUKvC.png

**Comment by daemitus** [comment]
^
