### ISSUE TITLE
Add option for Extract Materia

### ISSUE THREAD

**Issue by jcsanady** [daemitus/YesAlready#71]
I've been trying to add Extract Materia for spiritbonded items to the YesNo list without any luck.  It'd be nice if this one could be added to the default checklist similar to Retrieve Materia.

Thanks for the awesome mod!

**Comment by daemitus** [comment]
retrieve and extract are both in bothers.

**Comment by OpusNK** [comment]
I see "retrieve" and "remove" only in the bothers. No extract. Am I just blind or dumb?

**Comment by jcsanady** [comment]
This is what threw me, as well.  The option is there, the naming just doesn't match what's in game.

**Comment by daemitus** [comment]
retrieve is extract. ill clarify it  shortly.
