### ISSUE TITLE
Maximum match field length

### ISSUE THREAD

**Issue by PrincessRTFM** [daemitus/YesAlready#73]
The field to enter text or a regex to match against the popups has a maximum length of 100 characters, which isn't actually that much when it comes to regex matches. For instance, to skip discard confirmations on the Alexander raid drops, the following regex is needed:

> `/^Discard (the|\d+) (precision|tarnished) (Gordian|Midan|Alexandrian) (lense?|shaft|gear|crank|bolt|spring|pedal)s?\?/`

Unfortunately, this requires 118 characters, which means it can't be applied in a single match field. If this input length restriction could be removed (and, ideally, the editor mini-window made wider) then it would allow for more extensive text matches.

(Side note: it seems that _previously_ it was possible to use long inputs, since I have several that are over 100 characters long, but now it isn't. If I try to copy and paste from a long matcher, it fails. Was the change intentional?)

**Comment by daemitus** [comment]
bumped them all to 10_000
