### ISSUE TITLE
Self made Regex does not work correctly

### ISSUE THREAD

**Issue by Akurosia** [daemitus/YesAlready#8]
<img width="685" alt="ffxiv_dx11_RekpD75901" src="https://user-images.githubusercontent.com/7465469/112658080-56863d80-8e53-11eb-9bec-ff9960e29bb6.png">

used a simple regex `Mit \w+ \w+ einloggen?` to skip the question if you really want to login with my char (which wokred some days ago) but now it does not (had atleast 1 update of the plugin)

When i replace the \w+ with my actual char name, this works like expected.

Can you please have a look at this?

**Comment by daemitus** [comment]
Regex entries need to be defined as /yourregexgoeshere/

**Comment by Akurosia** [comment]
ok strange as it was working before without it, but can confirm it works now with the added /
