### ISSUE TITLE
Option for "Harvest Crop" / "Plant Seeds"

### ISSUE THREAD

**Issue by drejjmit** [daemitus/YesAlready#81]
Possible to add these as an option? Would speed up gardening by a lot

![image](https://user-images.githubusercontent.com/15526476/186579948-39240947-f538-4d4e-8bce-66d1ebfcfd63.png)

**Comment by guppyfaced** [comment]
I've created a page with my config, which automatically tends crops. You can use that as as template to see how you can harvest crops.

Not sure if you can automatically plants seeds though but it would be nice.

https://github.com/daemitus/YesAlready/wiki/Commonly-used-%22Yes-Already%22-configuration
