### ISSUE TITLE
Not able to instailed on Chinese client

### ISSUE THREAD

**Issue by blazbluecrazy** [daemitus/YesAlready#83]
Could you provide an old version of YesAlready and XIVCombo? New patch not able to load on Chinese client.

**Comment by guppyfaced** [comment]
Can you view the plugin but cannot enable it?

**Comment by FaGHX** [comment]
The update speed of the Dalamud plugin in China is not synchronized, so we cannot install the updated YesAlready.

**Comment by blazbluecrazy** [comment]
Chinese client still using Dalamud 6.4.0.46.

**Comment by daemitus** [comment]
https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/CN/pluginmaster.json

**Comment by blazbluecrazy** [comment]
I tried the CN link but Plugin still not able to install. After clicked the instail button, Dalamud will pop up a new window, "Failed to install plugin Yes Already. Please restart your game and try again....."
Dalamud 4.4.0.47, FFXIV 6.10

**Comment by daemitus** [comment]
I'm going to need the specific error from the logs

**Comment by blazbluecrazy** [comment]
Where can I find the logs for you?

**Comment by daemitus** [comment]
Screenshot when it happens in/xllog or from the dalamud.log file in
appdata/xivlauncher

**Comment by blazbluecrazy** [comment]
The error log when I tried to install from the CN link
![20220827153638](https://user-images.githubusercontent.com/46982803/187047155-38c08887-d9fa-438d-a873-4181d86cfe4f.png)

**Comment by FaGHX** [comment]
It has been installed through the CN link, but is not installed through dalamud, but is manually downloaded and imported into XIVLauncher\installedPlugins.
blazbluecrazy you can try this method

**Comment by blazbluecrazy** [comment]
I can see the Dalamud downloaded the file in my folder. It failed when loading.
I just tried using the download link and replaced the files from latest.zip,  here is the error log.
![20220827185848](https://user-images.githubusercontent.com/46982803/187051992-851c8e12-ea68-4b55-9720-99b69cecd618.png)

**Comment by FaGHX** [comment]
Is YesAlready\1.2.1.3 built like this? Need to unzip the .zip and import it

**Comment by blazbluecrazy** [comment]
I seem to notice that [daemitus](https://github.com/daemitus) didn't modify the CN/pluginmaster.json to CN download link, so I just re-downloaded a plugin from the CN branch. First time it crushed my game, but I just restart FFXIV and it works!

**Comment by FaGHX** [comment]
I can't use Dalamud to get the plug-in of the CN link, so I can only download it one by one and import it manually, and I just use YesAlready, so it's not a big problem for me.

**Comment by daemitus** [comment]
The download links were updated if your want to try again
