### ISSUE TITLE
更新后启用/安装失败

### ISSUE THREAD

**Issue by Hildakoaren** [daemitus/YesAlready#85]
紧急查阅过后才知晓大佬的库主要跟随国际服，如有烦扰万分抱歉……
在不知道情况的时候点了插件更新，然后目前库里的几个插件无法使用了，不知道大佬有没有旧版本的插件（在卫月上好像没看到回退）

**Comment by daemitus** [comment]
Use https://raw.githubusercontent.com/daemitus/MyDalamudPlugins/CN/pluginmaster.json

**Comment by Hildakoaren** [comment]
万分感谢！！十分抱歉梯子挂了几天！！谢谢您！！！
