### ISSUE TITLE
Feature Request: Automated "collect and resume caretaking" dialogues from the Island Sanctuary (farm/pasture)

### ISSUE THREAD

**Issue by kaedys** [daemitus/YesAlready#87]
The Talk and List options don't seem to handle these dropdowns, but it's a right pain right clicking on each, then clicking "collect and resume".  And if you miss and hit "collect and dismiss", it costs another 5 or 10 cowries to resume the caretaking, because they charge an extra amount when you start the caretaking.  Really, I'm hoping a mod eventually figures out how to automate the entire process of clicking through each one and collecting (and resuming), which maybe might even be in Yes Already's wheelhouse, since it has something sorta similar for Retainer Ventures, but unless/until then, be nice if I could just scroll down and right click on each in turn and it would take care of the "collect and resume" click.

**Comment by Kwehh13** [comment]
has anyone figured out how to make this work or does is it just not possible

**Comment by dafunks** [comment]
I have a little setup for this that works pretty well. Hopefully I can explain it and its helpful for you. 

I use: "Simple Tweaks Plugin" and the setting "Quick collect from Island Mammets" turned on.
I use: "YesAlready" (Obviously) and use these two settings:
-"Accept the following items?"
-"will be collected. Proceed?  Amount currently held"
I also select Zone Restricted for the island but it isn't needed.

To use it: Hold Shift and Right Click on each one. Takes seconds and its all done.
----------------
I hope I explained this OK. If not happy to help out. Would love YesAlready to be able to do all of this without using Simple Tweeks. It would be perfect but for now this works for me and I hope for you.

**Comment by kaedys** [comment]
This is probably no longer needed, since the base game has a "collect all" button that also resumes caretaking.  If someone disagrees, feel free to re-open.
