### ISSUE TITLE
configurable random delay

### ISSUE THREAD

**Issue by AmenneHolelane** [daemitus/YesAlready#9]
I'm wondering if it instantly accepting dialogue as it's presented could cause flags on SE's side. A configurable delay (something like 70-120 ms) might help prevent that. unless i'm misunderstanding how it works, then ignore me lol

**Comment by daemitus** [comment]
It still has to wait for the dialog to pop, So it's doing it as fast as the game would feasibly allow anyways if you spammed a click in the perfect spot. If i ever figure out how to skip the dialog completely, this would be worth revisiting imo.
